name: example
description: Examples for assorted_layout_widgets
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'

dependencies:
  assorted_layout_widgets:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
