name: assorted_layout_widgets
description: Assorted layout widgets that boldly go where no native Flutter widgets have gone before.
version: 1.0.0
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/assorted_layout_widgets

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.6.3
  flutter_test:
    sdk: flutter

flutter:
