name: assorted_layout_widgets
description: A lot of widgets like ColumnSuper, RowSuper, FitHorizontally, Box, WrapSuper, TextOneLine, Delayed, Pad, ButtonBarSuper, NormalizedOverflowBox, showDialogSuper, and much more.
version: 5.7.1
homepage: https://github.com/marcglasberg/assorted_layout_widgets
# author: Marcelo Glasberg <marcglasberg@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  clock: ^1.1.0
  flutter:
    sdk: flutter
  matrix4_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5

flutter:
